export const DETECTION_CONFIG = {
  HIGH_CONFIDENCE_THRESHOLD: 70,

  LOW_CONFIDENCE_THRESHOLD: 50,

  MAX_CONFIDENCE: 100,

  MIN_CONFIDENCE: 0,

  MIN_HORIZONTAL_LINE_LENGTH: 50,

  MAX_INPUT_LINE_HEIGHT: 5,

  MAX_LABEL_LINE_VERTICAL_DISTANCE: 60,

  MAX_LABEL_LINE_HORIZONTAL_DISTANCE: 250,

  MIN_SIGNATURE_WIDTH: 80,

  DEFAULT_SIGNATURE_WIDTH: 220,

  DEFAULT_SIGNATURE_HEIGHT: 55,

  SECTION_CONTEXT_DISTANCE: 250,

  DUPLICATE_X_DISTANCE: 100,

  DUPLICATE_Y_DISTANCE: 60,

  INDEX_DOTTED_LEADER_MIN_LENGTH: 3,

  INDEX_MAX_PAGE_NUMBER_DIGITS: 4,
} as const;
